package com.spartan.data.export

import com.spartan.data.local.MetricEntryEntity
import com.spartan.data.local.PlanWorkoutOverrideEntity
import com.spartan.data.local.ReminderEntity
import com.spartan.data.local.TargetEntity
import com.spartan.data.local.UserProfileEntity
import com.spartan.data.local.WorkoutSessionEntity
import java.time.LocalDate

object LocalExportFormatter {
    fun format(
        profile: UserProfileEntity?,
        metrics: List<MetricEntryEntity>,
        targets: List<TargetEntity>,
        workouts: List<WorkoutSessionEntity>,
        planOverrides: List<PlanWorkoutOverrideEntity> = emptyList(),
        reminders: List<ReminderEntity>,
    ): String = buildString {
        appendLine("Spartan Local Export")
        appendLine("Generated by local app export")
        appendLine()

        appendLine("[Profile]")
        appendLine(csv("id", "displayName", "heightCm", "birthYear", "sexAtBirth", "updatedAtMillis"))
        if (profile != null) {
            appendLine(csv(profile.id, profile.displayName, profile.heightCm, profile.birthYear, profile.sexAtBirth, profile.updatedAtMillis))
        }
        appendLine()

        appendLine("[Metrics]")
        appendLine(csv("id", "recordedDate", "type", "value", "unit", "note", "createdAtMillis"))
        metrics.forEach {
            appendLine(csv(it.id, LocalDate.ofEpochDay(it.recordedAtEpochDay), it.type.name, it.value ?: "pending", it.unit, it.note, it.createdAtMillis))
        }
        appendLine()

        appendLine("[Targets]")
        appendLine(csv("id", "metricType", "minValue", "maxValue", "note"))
        targets.forEach {
            appendLine(csv(it.id, it.metricType.name, it.minValue ?: "", it.maxValue ?: "", it.note))
        }
        appendLine()

        appendLine("[Workout logs]")
        appendLine(csv("id", "completedDate", "type", "plannedMinutes", "completedMinutes", "rpe", "painFlag"))
        workouts.forEach {
            appendLine(csv(it.id, LocalDate.ofEpochDay(it.completedAtEpochDay), it.type.name, it.plannedMinutes, it.completedMinutes, it.rpe, it.painFlag))
        }
        appendLine()

        appendLine("[Plan overrides]")
        appendLine(csv("slotKey", "minutes", "updatedAtMillis"))
        planOverrides.forEach {
            appendLine(csv(it.slotKey, it.minutes, it.updatedAtMillis))
        }
        appendLine()

        appendLine("[Reminders]")
        appendLine(csv("id", "title", "body", "hour", "minute", "enabled", "frequency", "daysOfWeekMask", "updatedAtMillis"))
        reminders.forEach {
            appendLine(csv(it.id, it.title, it.body, it.hour, it.minute, it.enabled, it.frequency.name, it.daysOfWeekMask, it.updatedAtMillis))
        }
    }

    private fun csv(vararg values: Any?): String = values.joinToString(",") { value ->
        val text = value?.toString().orEmpty()
        if (text.any { it == ',' || it == '"' || it == '\n' || it == '\r' }) {
            "\"" + text.replace("\"", "\"\"") + "\""
        } else {
            text
        }
    }
}
