import Foundation

/// Spartan coaching domain models.
///
/// A `DailyPlan` is a small, bounded list of `DailyActivity` items generated by the
/// rules-based `CoachingEngine` from a wearable-agnostic `ReadinessSnapshot`. These types are
/// deliberately free of any WHOOP/UIKit dependency so the engine stays pure and testable
/// and so additional wearables or an AI recommendation source can feed the same shapes later.
///
/// Faithful port of `com.spartan.domain.model.CoachingModels` (Android): same fields, same
/// band thresholds, same trend math, same user-facing trend copy.

public enum ActivityCategory: String, Codable, CaseIterable {
    case recovery = "RECOVERY"
    case movement = "MOVEMENT"
    case zone2 = "ZONE2"
    case strength = "STRENGTH"
    case mobility = "MOBILITY"
    case breathwork = "BREATHWORK"
    case sleep = "SLEEP"
    case hydration = "HYDRATION"
    case nutrition = "NUTRITION"
    case mindset = "MINDSET"
}

public enum ActivityPriority: String, Codable, CaseIterable {
    case required = "REQUIRED"
    case recommended = "RECOMMENDED"
    case optional = "OPTIONAL"

    /// Mirrors the Kotlin enum ordinal used to order plans (REQUIRED first, OPTIONAL last).
    public var sortRank: Int {
        switch self {
        case .required: return 0
        case .recommended: return 1
        case .optional: return 2
        }
    }
}

public enum ActivityStatus: String, Codable, CaseIterable {
    case planned = "PLANNED"
    case done = "DONE"
    case snoozed = "SNOOZED"
    case skipped = "SKIPPED"
    case rescheduled = "RESCHEDULED"
    case missed = "MISSED"
}

public enum Intensity: String, Codable, CaseIterable {
    case rest = "REST"
    case easy = "EASY"
    case moderate = "MODERATE"
    case hard = "HARD"
}

public enum TimeOfDay: String, Codable, CaseIterable {
    case morning = "MORNING"
    case midday = "MIDDAY"
    case afternoon = "AFTERNOON"
    case evening = "EVENING"
    case anytime = "ANYTIME"
}

/// Recovery band derived from a recovery score. See `ReadinessBand.fromRecovery(_:)`.
public enum ReadinessBand: String, Codable, CaseIterable {
    case primed = "PRIMED"
    case balanced = "BALANCED"
    case easy = "EASY"
    case rest = "REST"

    /// Same thresholds as Android: >= 67 PRIMED, >= 50 BALANCED, >= 34 EASY, else REST;
    /// a missing score resolves to BALANCED.
    public static func fromRecovery(_ recoveryScore: Int?) -> ReadinessBand {
        guard let score = recoveryScore else { return .balanced }
        if score >= 67 { return .primed }
        if score >= 50 { return .balanced }
        if score >= 34 { return .easy }
        return .rest
    }
}

/// Wearable-normalized daily data (from WHOOP today) plus enough context to detect trends.
/// `isMock` is true whenever the values came from the sample data source.
public struct WhoopSnapshot: Codable, Equatable {
    public let dateEpochDay: Int
    public let recoveryScore: Int?
    public let hrvMs: Double?
    public let restingHeartRate: Double?
    public let sleepPerformance: Int?
    public let sleepDurationHours: Double?
    public let sleepDebtHours: Double?
    public let respiratoryRate: Double?
    public let dayStrain: Double?
    public let energyKcal: Double?
    /// Local minute-of-day the user typically fell asleep / woke, from the sleep record.
    public let bedMinuteOfDay: Int?
    public let wakeMinuteOfDay: Int?
    public let isMock: Bool

    public init(
        dateEpochDay: Int,
        recoveryScore: Int? = nil,
        hrvMs: Double? = nil,
        restingHeartRate: Double? = nil,
        sleepPerformance: Int? = nil,
        sleepDurationHours: Double? = nil,
        sleepDebtHours: Double? = nil,
        respiratoryRate: Double? = nil,
        dayStrain: Double? = nil,
        energyKcal: Double? = nil,
        bedMinuteOfDay: Int? = nil,
        wakeMinuteOfDay: Int? = nil,
        isMock: Bool = false
    ) {
        self.dateEpochDay = dateEpochDay
        self.recoveryScore = recoveryScore
        self.hrvMs = hrvMs
        self.restingHeartRate = restingHeartRate
        self.sleepPerformance = sleepPerformance
        self.sleepDurationHours = sleepDurationHours
        self.sleepDebtHours = sleepDebtHours
        self.respiratoryRate = respiratoryRate
        self.dayStrain = dayStrain
        self.energyKcal = energyKcal
        self.bedMinuteOfDay = bedMinuteOfDay
        self.wakeMinuteOfDay = wakeMinuteOfDay
        self.isMock = isMock
    }
}

/// The CoachingEngine input. Wearable-agnostic: built from a `WhoopSnapshot` today plus recent
/// history via `from(today:history:)`. Carries derived trend deltas and the resolved `band`.
public struct ReadinessSnapshot: Codable, Equatable {
    public let dateEpochDay: Int
    public let recoveryScore: Int?
    public let hrvMs: Double?
    public let hrvVsBaseline: Double?
    public let restingHeartRate: Double?
    public let rhrVsBaseline: Double?
    public let sleepPerformance: Int?
    public let sleepDebtHours: Double?
    public let dayStrainPrior: Double?
    public let respiratoryRate: Double?
    public let respiratoryRateBaseline: Double?
    public let band: ReadinessBand
    public let trendNotes: [String]
    public let isStale: Bool
    public let isMock: Bool

    public init(
        dateEpochDay: Int,
        recoveryScore: Int? = nil,
        hrvMs: Double? = nil,
        hrvVsBaseline: Double? = nil,
        restingHeartRate: Double? = nil,
        rhrVsBaseline: Double? = nil,
        sleepPerformance: Int? = nil,
        sleepDebtHours: Double? = nil,
        dayStrainPrior: Double? = nil,
        respiratoryRate: Double? = nil,
        respiratoryRateBaseline: Double? = nil,
        band: ReadinessBand = .balanced,
        trendNotes: [String] = [],
        isStale: Bool = false,
        isMock: Bool = false
    ) {
        self.dateEpochDay = dateEpochDay
        self.recoveryScore = recoveryScore
        self.hrvMs = hrvMs
        self.hrvVsBaseline = hrvVsBaseline
        self.restingHeartRate = restingHeartRate
        self.rhrVsBaseline = rhrVsBaseline
        self.sleepPerformance = sleepPerformance
        self.sleepDebtHours = sleepDebtHours
        self.dayStrainPrior = dayStrainPrior
        self.respiratoryRate = respiratoryRate
        self.respiratoryRateBaseline = respiratoryRateBaseline
        self.band = band
        self.trendNotes = trendNotes
        self.isStale = isStale
        self.isMock = isMock
    }

    /// Build a readiness snapshot for `today` using `history` (older snapshots, any order)
    /// to compute simple baselines/trends. History should exclude today.
    public static func from(today: WhoopSnapshot, history: [WhoopSnapshot] = []) -> ReadinessSnapshot {
        let priorSorted = history
            .filter { $0.dateEpochDay < today.dateEpochDay }
            .sorted { $0.dateEpochDay < $1.dateEpochDay }

        func average(_ values: [Double]) -> Double? {
            guard !values.isEmpty else { return nil }
            return values.reduce(0, +) / Double(values.count)
        }

        let hrvBaseline = average(priorSorted.compactMap { $0.hrvMs })
        let rhrBaseline = average(priorSorted.compactMap { $0.restingHeartRate })
        let rrBaseline = average(priorSorted.compactMap { $0.respiratoryRate })
        let priorStrain = priorSorted.last?.dayStrain

        var notes: [String] = []
        var hrvDelta: Double? = nil
        if let hrv = today.hrvMs, let baseline = hrvBaseline {
            let delta = hrv - baseline
            hrvDelta = delta
            if delta <= -0.1 * baseline {
                notes.append("HRV is trending below your recent baseline.")
            }
        }
        var rhrDelta: Double? = nil
        if let rhr = today.restingHeartRate, let baseline = rhrBaseline {
            let delta = rhr - baseline
            rhrDelta = delta
            if delta >= 5.0 {
                notes.append("Resting heart rate is elevated versus your recent baseline.")
            }
        }

        return ReadinessSnapshot(
            dateEpochDay: today.dateEpochDay,
            recoveryScore: today.recoveryScore,
            hrvMs: today.hrvMs,
            hrvVsBaseline: hrvDelta,
            restingHeartRate: today.restingHeartRate,
            rhrVsBaseline: rhrDelta,
            sleepPerformance: today.sleepPerformance,
            sleepDebtHours: today.sleepDebtHours,
            dayStrainPrior: priorStrain,
            respiratoryRate: today.respiratoryRate,
            respiratoryRateBaseline: rrBaseline,
            band: ReadinessBand.fromRecovery(today.recoveryScore),
            trendNotes: notes,
            isStale: today.recoveryScore == nil,
            isMock: today.isMock
        )
    }
}

/// The WHOOP-derived metrics a coaching activity can reference (the subset of Android's
/// MetricType the coaching layer uses; the lab-metric catalog remains Android-only for now).
/// Raw values match the Android enum names for cross-platform data parity.
public enum MetricType: String, Codable, CaseIterable {
    case recoveryScore = "RECOVERY_SCORE"
    case hrvRmssd = "HRV_RMSSD"
    case sleepPerformance = "SLEEP_PERFORMANCE"
    case sleepDebt = "SLEEP_DEBT"
    case respiratoryRate = "RESPIRATORY_RATE"
    case dayStrain = "DAY_STRAIN"
    case restingHeartRate = "RESTING_HEART_RATE"
    case sleepDuration = "SLEEP_DURATION"
    case energyKcal = "ENERGY_KCAL"
}

/// One concrete, actionable item in a daily plan.
public struct DailyActivity: Codable, Equatable, Identifiable {
    public let id: String
    public let title: String
    public let category: ActivityCategory
    public let priority: ActivityPriority
    public let whyItMatters: String
    public let relatedMetric: MetricType?
    public let instructions: [String]
    public let estimatedMinutes: Int
    public let intensity: Intensity
    public let bestTimeOfDay: TimeOfDay
    public var status: ActivityStatus
    public let ruleId: String
    public var scheduledEpochMinute: Int?
    public var completedAtMillis: Int?
    public var snoozedUntilMillis: Int?
    public let safetyNote: String?

    public init(
        id: String,
        title: String,
        category: ActivityCategory,
        priority: ActivityPriority,
        whyItMatters: String,
        relatedMetric: MetricType? = nil,
        instructions: [String] = [],
        estimatedMinutes: Int,
        intensity: Intensity,
        bestTimeOfDay: TimeOfDay,
        status: ActivityStatus = .planned,
        ruleId: String,
        scheduledEpochMinute: Int? = nil,
        completedAtMillis: Int? = nil,
        snoozedUntilMillis: Int? = nil,
        safetyNote: String? = nil
    ) {
        self.id = id
        self.title = title
        self.category = category
        self.priority = priority
        self.whyItMatters = whyItMatters
        self.relatedMetric = relatedMetric
        self.instructions = instructions
        self.estimatedMinutes = estimatedMinutes
        self.intensity = intensity
        self.bestTimeOfDay = bestTimeOfDay
        self.status = status
        self.ruleId = ruleId
        self.scheduledEpochMinute = scheduledEpochMinute
        self.completedAtMillis = completedAtMillis
        self.snoozedUntilMillis = snoozedUntilMillis
        self.safetyNote = safetyNote
    }
}

/// A whole day's recommended plan.
public struct DailyPlan: Codable, Equatable {
    public let dateEpochDay: Int
    public let headline: String
    public let band: ReadinessBand
    public var activities: [DailyActivity]
    public let safetyBanner: String?
    public let isMock: Bool

    public init(
        dateEpochDay: Int,
        headline: String,
        band: ReadinessBand,
        activities: [DailyActivity],
        safetyBanner: String? = nil,
        isMock: Bool = false
    ) {
        self.dateEpochDay = dateEpochDay
        self.headline = headline
        self.band = band
        self.activities = activities
        self.safetyBanner = safetyBanner
        self.isMock = isMock
    }

    public var totalEstimatedMinutes: Int {
        activities.reduce(0) { $0 + $1.estimatedMinutes }
    }

    public var completedCount: Int {
        activities.filter { $0.status == .done }.count
    }

    public var progressPercent: Int {
        guard !activities.isEmpty else { return 0 }
        return (completedCount * 100) / activities.count
    }
}

/// A free window on the user's calendar, expressed in epoch minutes (UTC).
public struct TimeWindow: Codable, Equatable {
    public let startEpochMinute: Int
    public let endEpochMinute: Int

    public init(startEpochMinute: Int, endEpochMinute: Int) {
        self.startEpochMinute = startEpochMinute
        self.endEpochMinute = endEpochMinute
    }

    public var durationMinutes: Int {
        max(endEpochMinute - startEpochMinute, 0)
    }
}
