package com.spartan.domain.model

/**
 * Spartan coaching domain models.
 *
 * A [DailyPlan] is a small, bounded list of [DailyActivity] items generated by the
 * rules-based CoachingEngine from a wearable-agnostic [ReadinessSnapshot]. These types are
 * deliberately free of any WHOOP/Android dependency so the engine stays pure and testable
 * and so additional wearables or an AI recommendation source can feed the same shapes later.
 */

enum class ActivityCategory {
    RECOVERY, MOVEMENT, ZONE2, STRENGTH, MOBILITY, BREATHWORK, SLEEP, HYDRATION, NUTRITION, MINDSET
}

enum class ActivityPriority { REQUIRED, RECOMMENDED, OPTIONAL }

enum class ActivityStatus { PLANNED, DONE, SNOOZED, SKIPPED, RESCHEDULED, MISSED }

enum class Intensity { REST, EASY, MODERATE, HARD }

enum class TimeOfDay { MORNING, MIDDAY, AFTERNOON, EVENING, ANYTIME }

/** Recovery band derived from a recovery score. See [ReadinessBand.fromRecovery]. */
enum class ReadinessBand {
    PRIMED, BALANCED, EASY, REST;

    companion object {
        fun fromRecovery(recoveryScore: Int?): ReadinessBand = when {
            recoveryScore == null -> BALANCED
            recoveryScore >= 67 -> PRIMED
            recoveryScore >= 50 -> BALANCED
            recoveryScore >= 34 -> EASY
            else -> REST
        }
    }
}

/**
 * Wearable-normalized daily data (from WHOOP today) plus enough context to detect trends.
 * `isMock` is true whenever the values came from the sample data source.
 */
data class WhoopSnapshot(
    val dateEpochDay: Long,
    val recoveryScore: Int? = null,
    val hrvMs: Double? = null,
    val restingHeartRate: Double? = null,
    val sleepPerformance: Int? = null,
    val sleepDurationHours: Double? = null,
    val sleepDebtHours: Double? = null,
    val respiratoryRate: Double? = null,
    val dayStrain: Double? = null,
    val energyKcal: Double? = null,
    /** Local minute-of-day the user typically fell asleep / woke, from the sleep record. */
    val bedMinuteOfDay: Int? = null,
    val wakeMinuteOfDay: Int? = null,
    val isMock: Boolean = false,
)

/**
 * The CoachingEngine input. Wearable-agnostic: built from a [WhoopSnapshot] today plus recent
 * history via [from]. Carries derived trend deltas and the resolved [band].
 */
data class ReadinessSnapshot(
    val dateEpochDay: Long,
    val recoveryScore: Int? = null,
    val hrvMs: Double? = null,
    val hrvVsBaseline: Double? = null,
    val restingHeartRate: Double? = null,
    val rhrVsBaseline: Double? = null,
    val sleepPerformance: Int? = null,
    val sleepDebtHours: Double? = null,
    val dayStrainPrior: Double? = null,
    val respiratoryRate: Double? = null,
    val respiratoryRateBaseline: Double? = null,
    val band: ReadinessBand = ReadinessBand.BALANCED,
    val trendNotes: List<String> = emptyList(),
    val isStale: Boolean = false,
    val isMock: Boolean = false,
) {
    companion object {
        /**
         * Build a readiness snapshot for [today] using [history] (older snapshots, any order)
         * to compute simple baselines/trends. History should exclude today.
         */
        fun from(today: WhoopSnapshot, history: List<WhoopSnapshot> = emptyList()): ReadinessSnapshot {
            val priorSorted = history.filter { it.dateEpochDay < today.dateEpochDay }
                .sortedBy { it.dateEpochDay }
            val hrvBaseline = priorSorted.mapNotNull { it.hrvMs }.takeIf { it.isNotEmpty() }?.average()
            val rhrBaseline = priorSorted.mapNotNull { it.restingHeartRate }.takeIf { it.isNotEmpty() }?.average()
            val rrBaseline = priorSorted.mapNotNull { it.respiratoryRate }.takeIf { it.isNotEmpty() }?.average()
            val priorStrain = priorSorted.lastOrNull()?.dayStrain

            val notes = mutableListOf<String>()
            val hrvDelta = if (today.hrvMs != null && hrvBaseline != null) today.hrvMs - hrvBaseline else null
            if (hrvDelta != null && hrvBaseline != null && hrvDelta <= -0.1 * hrvBaseline) {
                notes += "HRV is trending below your recent baseline."
            }
            val rhrDelta = if (today.restingHeartRate != null && rhrBaseline != null) today.restingHeartRate - rhrBaseline else null
            if (rhrDelta != null && rhrDelta >= 5.0) {
                notes += "Resting heart rate is elevated versus your recent baseline."
            }

            return ReadinessSnapshot(
                dateEpochDay = today.dateEpochDay,
                recoveryScore = today.recoveryScore,
                hrvMs = today.hrvMs,
                hrvVsBaseline = hrvDelta,
                restingHeartRate = today.restingHeartRate,
                rhrVsBaseline = rhrDelta,
                sleepPerformance = today.sleepPerformance,
                sleepDebtHours = today.sleepDebtHours,
                dayStrainPrior = priorStrain,
                respiratoryRate = today.respiratoryRate,
                respiratoryRateBaseline = rrBaseline,
                band = ReadinessBand.fromRecovery(today.recoveryScore),
                trendNotes = notes,
                isStale = today.recoveryScore == null,
                isMock = today.isMock,
            )
        }
    }
}

/** One concrete, actionable item in a daily plan. */
data class DailyActivity(
    val id: String,
    val title: String,
    val category: ActivityCategory,
    val priority: ActivityPriority,
    val whyItMatters: String,
    val relatedMetric: MetricType? = null,
    val instructions: List<String> = emptyList(),
    val estimatedMinutes: Int,
    val intensity: Intensity,
    val bestTimeOfDay: TimeOfDay,
    val status: ActivityStatus = ActivityStatus.PLANNED,
    val ruleId: String,
    val scheduledEpochMinute: Long? = null,
    val completedAtMillis: Long? = null,
    val snoozedUntilMillis: Long? = null,
    val safetyNote: String? = null,
)

/** A whole day's recommended plan. */
data class DailyPlan(
    val dateEpochDay: Long,
    val headline: String,
    val band: ReadinessBand,
    val activities: List<DailyActivity>,
    val safetyBanner: String? = null,
    val isMock: Boolean = false,
) {
    val totalEstimatedMinutes: Int get() = activities.sumOf { it.estimatedMinutes }
    val completedCount: Int get() = activities.count { it.status == ActivityStatus.DONE }
    val progressPercent: Int
        get() = if (activities.isEmpty()) 0 else (completedCount * 100) / activities.size
}

/** A free window on the user's calendar, expressed in epoch minutes (UTC). */
data class TimeWindow(
    val startEpochMinute: Long,
    val endEpochMinute: Long,
) {
    val durationMinutes: Long get() = (endEpochMinute - startEpochMinute).coerceAtLeast(0)
}
